YAML mode

diff --git a/unitc b/unitc
--- a/unitc
+++ b/unitc
@@ -1,7 +1,7 @@
 #!/bin/bash
 # unitc - a curl wrapper for configuring NGINX Unit
 # https://github.com/nginx/unit/tree/master/tools
-# NGINX, Inc. (c) 2022
+# NGINX, Inc. (c) 2023
 
 # Defaults
 #
@@ -10,6 +10,7 @@ REMOTE=0
 SHOW_LOG=1
 NOLOG=0
 QUIET=0
+YAML=0
 URI=""
 SSH_CMD=""
 METHOD=PUT
@@ -32,7 +33,19 @@ while [ $# -gt 0 ]; do
 			shift
 			;;
 
-		"GET" | "PUT" | "POST" | "DELETE" | "INSERT")
+		"-Y" | "--YAML")
+			YAML=1
+			if hash yq 2> /dev/null; then
+				YAML2JSON="yq eval -P --output-format=json"
+				JSON2YAML="yq eval -P --output-format=yaml"
+			else
+				echo "${0##*/}: ERROR: yq(1) is required to use YAML configuration; install at <https://github.com/mikefarah/yq#install>"
+				exit 1
+			fi
+			shift
+			;;
+
+		"GET" | "PUT" | "POST" | "DELETE" | "INSERT" | "EDIT")
 			METHOD=$OPTION
 			shift
 			;;
@@ -43,17 +56,24 @@ while [ $# -gt 0 ]; do
 			;;
 
 		*)
-			if [ -r $1 ]; then
+			if [ -f $1 ] && [ -r $1 ]; then
 				CONF_FILES+=($1)
+				if [ "${1##*.}" == "yaml" ]; then
+					echo "${0##*/}: INFO: converting $1 to JSON"
+					shift; set -- "--yaml" "$@" # Force the --yaml option
+				else
+					shift
+				fi
 			elif [ "${1:0:1}" = "/" ] || [ "${1:0:4}" = "http" ] && [ "$URI" = "" ]; then
 				URI=$1
+				shift
 			elif [ "${1:0:6}" = "ssh://" ]; then
 				UNIT_CTRL=$1
+				shift
 			else
 				echo "${0##*/}: ERROR: Invalid option ($1)"
 				exit 1
 			fi
-			shift
 			;;
 	esac
 done
@@ -71,8 +91,10 @@ USAGE: ${0##*/} [options] URI
 General options
   filename …    # Read configuration data from files instead of stdin
   HTTP method   # Default=GET, or PUT with config data (case-insensitive)
+  EDIT          # Opens the URI contents in \$EDITOR
   INSERT        # Virtual HTTP method to prepend data to an existing array
   -q | --quiet  # No output to stdout
+  -y | --yaml   # Treat configuration data as YAML (converts to/from JSON)
 
 Local options
   -l | --nolog  # Do not monitor the error log after applying config changes
@@ -121,20 +143,31 @@ if [ $REMOTE -eq 0 ]; then
 	if [ -r /tmp/${0##*/}.$PID.env ]; then
 		source /tmp/${0##*/}.$PID.env
 	else
-		# Check we have unitd in $PATH (and all the other tools we will need)
+		# Check we have all the tools we will need (that we didn't already use)
 		#
-		MISSING=$(hash unitd curl ps grep tr cut sed tail sleep 2>&1 | cut -f4 -d: | tr -d '\n')
+		MISSING=$(hash curl tr cut sed tail sleep 2>&1 | cut -f4 -d: | tr -d '\n')
 		if [ "$MISSING" != "" ]; then
 			echo "${0##*/}: ERROR: cannot find$MISSING: please install or add to \$PATH"
 			exit 1
 		fi
 
-		# Get control address
+		# Obtain any optional startup parameters from the 'unitd: main' process
+		# so we can get the actual control address and error log location.
+		# Command line options and output of ps(1) is notoriously variable across
+		# different *nix/BSD platforms so multiple attempts might be needed.
 		#
-		PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f4- -d ' ' | sed -e 's/ --/\n--/g')
+		PARAMS=$((ps -wwo args=COMMAND -p $PID || ps $PID) 2> /dev/null | grep unit | tr '[]' ^ | cut -f2 -d^ | sed -e 's/ --/\n--/g')
+		if [ "$PARAMS" = "" ]; then
+			echo "${0##*/}: WARNING: unable to identify unitd command line parameters for PID $PID, assuming unitd defaults from \$PATH"
+			PARAMS=unitd
+		fi
 		CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ')
 		if [ "$CTRL_ADDR" = "" ]; then
-			CTRL_ADDR=$(unitd --help | grep -A1 '\--control' | tail -1 |  cut -f2 -d\")
+			CTRL_ADDR=$($(echo "$PARAMS") --help | grep -A1 '\--control' | tail -1 | cut -f2 -d\")
+		fi
+		if [ "$CTRL_ADDR" = "" ]; then
+			echo "${0##*/}: ERROR: cannot detect control socket. Did you start unitd with a relative path? Try starting unitd with --control option."
+			exit 2
 		fi
 
 		# Prepare for network or Unix socket addressing
@@ -156,12 +189,16 @@ if [ $REMOTE -eq 0 ]; then
 		#
 		ERROR_LOG=$(echo "$PARAMS" | grep '\--log' | cut -f2 -d' ')
 		if [ "$ERROR_LOG" = "" ]; then
-			ERROR_LOG=$(unitd --help | grep -A1 '\--log' | tail -1 | cut -f2 -d\")
+			ERROR_LOG=$($(echo "$PARAMS") --help | grep -A1 '\--log' | tail -1 | cut -f2 -d\")
+		fi
+		if [ "$ERROR_LOG" = "" ]; then
+			echo "${0##*/}: WARNING: cannot detect unit log file (will not be monitored). If you started unitd from a relative path then try using the --log option."
+			ERROR_LOG=/dev/null
 		fi
 
 		# Cache the discovery for this unit PID (and cleanup any old files)
 		#
-		rm /tmp/${0##*/}.* 2> /dev/null
+		rm -f /tmp/${0##*/}.* 2> /dev/null
 		echo UNIT_CTRL=\"${UNIT_CTRL}\" > /tmp/${0##*/}.$PID.env
 		echo ERROR_LOG=${ERROR_LOG} >> /tmp/${0##*/}.$PID.env
 	fi
@@ -170,7 +207,9 @@ fi
 # Choose presentation style
 #
 if [ $QUIET -eq 1 ]; then
-	OUTPUT="head -c 0" # Equivalent to >/dev/null
+	OUTPUT="tail -c 0" # Equivalent to >/dev/null
+elif [ $YAML -eq 1 ]; then
+	OUTPUT=$JSON2YAML
 elif hash jq 2> /dev/null; then
 	OUTPUT="jq"
 else
@@ -190,6 +229,33 @@ fi
 if [ -t 0 ] && [ ${#CONF_FILES[@]} -eq 0 ]; then
 	if [ "$METHOD" = "DELETE" ]; then
 		$SSH_CMD curl -X $METHOD $UNIT_CTRL$URI 2> /tmp/${0##*/}.$$ | $OUTPUT
+	elif [ "$METHOD" = "EDIT" ]; then
+		EDITOR=$(test "$EDITOR" && printf '%s' "$EDITOR" || command -v editor || command -v vim || echo vi)
+		EDIT_FILENAME=/tmp/${0##*/}.$$${URI//\//_}
+		$SSH_CMD curl -fsS $UNIT_CTRL$URI > $EDIT_FILENAME || exit 2
+		if [ "${URI:0:12}" = "/js_modules/" ]; then
+			if ! hash jq 2> /dev/null; then
+				echo "${0##*/}: ERROR: jq(1) is required to edit JavaScript modules; install at <https://stedolan.github.io/jq/>"
+				exit 1
+			fi
+			jq -r < $EDIT_FILENAME > $EDIT_FILENAME.js # Unescape linebreaks for a better editing experience
+			EDIT_FILE=$EDIT_FILENAME.js
+			$EDITOR $EDIT_FILENAME.js || exit 2
+			# Remove the references, delete old config, push new config+reference
+			$SSH_CMD curl -fsS $UNIT_CTRL/config/settings/js_module > /tmp/${0##*/}.$$_js_module && \
+			$SSH_CMD curl -X DELETE $UNIT_CTRL/config/settings/js_module && \
+			$SSH_CMD curl -fsSX DELETE $UNIT_CTRL$URI 2> /tmp/${0##*/}.$$ && \
+			printf "%s" "$(< $EDIT_FILENAME.js)" | $SSH_CMD curl -fX PUT --data-binary @- $UNIT_CTRL$URI 2> /tmp/${0##*/}.$$ && \
+			$SSH_CMD curl -X PUT --data-binary @/tmp/${0##*/}.$$_js_module $UNIT_CTRL/config/settings/js_module 2> /tmp/${0##*/}.$$
+		elif [ $YAML -eq 1 ]; then
+			$JSON2YAML < $EDIT_FILENAME > $EDIT_FILENAME.yaml
+			$EDITOR $EDIT_FILENAME.yaml || exit 2
+			$YAML2JSON < $EDIT_FILENAME.yaml | $SSH_CMD curl -X PUT --data-binary @- $UNIT_CTRL$URI 2> /tmp/${0##*/}.$$ | $OUTPUT
+		else
+			tr -d '\r' < $EDIT_FILENAME > $EDIT_FILENAME.json # Remove carriage-return from newlines
+			$EDITOR $EDIT_FILENAME.json || exit 2
+			$SSH_CMD curl -X PUT --data-binary @$EDIT_FILENAME.json $UNIT_CTRL$URI 2> /tmp/${0##*/}.$$ | $OUTPUT
+		fi
 	else
 		SHOW_LOG=$(echo $URI | grep -c ^/control/)
 		$SSH_CMD curl $UNIT_CTRL$URI 2> /tmp/${0##*/}.$$ | $OUTPUT
@@ -210,6 +276,10 @@ else
 			exit 3
 		fi
 	else
+		if [ $YAML -eq 1 ]; then
+			cat ${CONF_FILES[@]} | $YAML2JSON > /tmp/${0##*/}.$$_json
+			CONF_FILES=(/tmp/${0##*/}.$$_json)
+		fi
 		cat ${CONF_FILES[@]} | $SSH_CMD curl -X $METHOD --data-binary @- $UNIT_CTRL$URI 2> /tmp/${0##*/}.$$ | $OUTPUT
 	fi
 fi
@@ -221,11 +291,11 @@ if [ $CURL_STATUS -ne 0 ]; then
 		echo "${0##*/}: Check that you have permission to access the Unit control socket, or try again with sudo(8)"
 	else
 		echo "${0##*/}: Trying to access $UNIT_CTRL$URI"
-		cat /tmp/${0##*/}.$$ && rm /tmp/${0##*/}.$$
+		cat /tmp/${0##*/}.$$ && rm -f /tmp/${0##*/}.$$
 	fi
 	exit 4
 fi
-rm /tmp/${0##*/}.$$ 2> /dev/null
+rm -f /tmp/${0##*/}.$$* 2> /dev/null
 
 if [ $SHOW_LOG -gt 0 ] && [ $NOLOG -eq 0 ] && [ $QUIET -eq 0 ]; then
 	echo -n "${0##*/}: Waiting for log..."
