added remote option

diff --git a/unitc b/unitc
--- a/unitc
+++ b/unitc
@@ -5,59 +5,28 @@
 # Defaults
 #
 QUIET=0
-METHOD=PUT
+#METHOD=PUT
+BOLD=$(tput smso)
+NORM=$(tput rmso)
 SHOW_LOG=1
-URI=""
+#URI=""
 
 usage() {
+        if [ $# -gt 0 ]
+        then
+          local varname=$1
+          echo "${BOLD} $varname is missing please set $varname and try again."
+          echo ${NORM}
+        fi
+
+	echo "${0##*/} - a curl wrapper for configuring NGINX Unit"
+	echo ""
 	echo "-h: This message"
 	echo "-m: <method> GET / PUT / POST / DELETE / INSERT"
 	echo "-u: <uri> URI or unit config path"
-}
-
-check_unit_running() {
-  # Check if Unit is running, find the main process
-  #
-  PID=($(ps ax | grep unit:\ main | grep -v \ grep | awk '{print $1}'))
-  if [ ${#PID[@]} -eq 0 ]; then
-  	echo "${0##*/}: ERROR: unitd not running"
-  	exit 1
-  elif [ ${#PID[@]} -gt 1 ]; then
-  	echo "${0##*/}: ERROR: multiple unitd processes detected (${PID[@]})"
-  	exit 1
-  fi
-}
-
-while getopts "m:u:h" o; do
-    case "${o}" in
-        h)
-            usage
-            ;;
-        m)
-            METHOD=$(echo ${OPTARG} | tr '[a-z]' '[A-Z]')
-            ;;
-	u)
-	    URI=${OPTARG}
-	    ;;
-        *)
-            usage
-            ;;
-    esac
-done
-shift $((OPTIND-1))
-
-check_unit_running
-
-#if [ -z "${s}" ] || [ -z "${p}" ]; then
-#    usage
-#fi
-
-
-if [ "$URI" = "" ]; then
-	echo "${0##*/} - a curl wrapper for configuring NGINX Unit"
-	echo ""
-	echo "USAGE: ${0##*/} [--quiet] [HTTP method] URI"
-	echo ""
+        echo "-i: <IP> IP address of remote host"
+        echo "-p: <port> port on remote host (80 is default)"
+        echo ""
 	echo " URI is for the Unit configuration API, e.g. /config"
 	echo " --quiet (-q) Will not monitor the error log after config changes"
 	echo ""
@@ -68,7 +37,77 @@ if [ "$URI" = "" ]; then
 	echo " • The control socket is automatically detected"
 	echo ""
 	exit 1
-fi
+}
+
+check_unit_running() {
+  # Check if Unit is running, find the main process
+  #
+  PID=($(ps ax | grep unit:\ main | grep -v \ grep | awk '{print $1}'))
+  if [ ${#PID[@]} -eq 0 ]; then
+  	echo "${0##*/}: INFO: unitd not running locally.... assuming remote"
+        IS_REMOTE=true
+  	#echo "${0##*/}: ERROR: unitd not running"
+  	#exit 1
+  elif [ ${#PID[@]} -gt 1 ]; then
+  	echo "${0##*/}: ERROR: multiple unitd processes detected (${PID[@]})"
+  	exit 1
+  else 
+        IS_REMOTE=false
+  fi
+}
+
+while getopts "i:m:p:u:h" o; do
+    case "${o}" in
+        h)
+            usage
+            ;;
+        m)
+            METHOD=$(echo ${OPTARG} | tr '[a-z]' '[A-Z]')
+            ;;
+	u)
+	    URI=${OPTARG}
+	    ;;
+        i)  REMOTE_IP=${OPTARG}
+            ;;
+        p)  REMOTE_PORT=${OPTARG}
+            ;;
+        *)
+            usage
+            ;;
+    esac
+done
+[ $# = 0 ] && usage
+[ -z "$METHOD" ] && usage method
+[ -z "$URI" ] && usage uri
+
+shift $((OPTIND-1))
+
+check_unit_running
+[[ -z "${REMOTE_IP}" ]] && echo "foo"
+[[ -z "${REMOTE_PORT}" ]] && echo "foo"
+echo $REMOTE_HOST
+echo $REMOTE_IP
+echo $REMOTE_PORT
+
+#if [ -z "${s}" ] || [ -z "${p}" ]; then
+#    usage
+#fi
+
+
+#if [ "$URI" = "" ]; then
+#	echo "USAGE: ${0##*/} [--quiet] [HTTP method] URI"
+#	echo ""
+#	echo " URI is for the Unit configuration API, e.g. /config"
+#	echo " --quiet (-q) Will not monitor the error log after config changes"
+#	echo ""
+#	echo " • Configuration JSON is read from stdin"
+#	echo " • Default HTTP method is PUT for config changes, else GET"
+#	echo " • Virtual method INSERT adds to beginning of array"
+#	echo " • Options can appear in any position, e.g. method after URI"
+#	echo " • The control socket is automatically detected"
+#	echo ""
+#	exit 1
+#fi
 
 
 # Read the significant unitd conifuration from cache file (or create it)
@@ -84,28 +123,34 @@ else
 		exit 1
 	fi
 
-	PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f4- -d ' ' | sed -e 's/ --/\n--/g')
+#### Only do this is REMOTE not true
+        if [ "$IS_REMOTE" = "false" ] ; then
+	        PARAMS=$(ps $PID | grep unitd | cut -f2- -dv | tr '[]' ' ' | cut -f4- -d ' ' | sed -e 's/ --/\n--/g')
 
-	# Get control address
-	#
-	CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ')
-	if [ "$CTRL_ADDR" = "" ]; then
-		CTRL_ADDR=$(unitd --help | grep -A1 '\--control' | tail -1 |  cut -f2 -d\")
-	fi
+	        # Get control address
+	        #
+	        CTRL_ADDR=$(echo "$PARAMS" | grep '\--control' | cut -f2 -d' ')
+	        if [ "$CTRL_ADDR" = "" ]; then
+	        	CTRL_ADDR=$(unitd --help | grep -A1 '\--control' | tail -1 |  cut -f2 -d\")
+	        fi
 
-	# Prepare for network or Unix socket addressing
-	#
-	if [ $(echo $CTRL_ADDR | grep -c ^unix:) -eq 1 ]; then
-		SOCK_FILE=$(echo $CTRL_ADDR | cut -f2- -d:)
-		if [ -r $SOCK_FILE ]; then
-			CURL_ADDR="--unix-socket $SOCK_FILE _"
-		else
-			echo "${0##*/}: ERROR: cannot read unitd control socket: $SOCK_FILE"
-			ls -l $SOCK_FILE
-			exit 2
-		fi
+	        # Prepare for network or Unix socket addressing
+	        #
+	        if [ $(echo $CTRL_ADDR | grep -c ^unix:) -eq 1 ]; then
+	        	SOCK_FILE=$(echo $CTRL_ADDR | cut -f2- -d:)
+	        	if [ -r $SOCK_FILE ]; then
+	        		CURL_ADDR="--unix-socket $SOCK_FILE _"
+	        	else
+	        		echo "${0##*/}: ERROR: cannot read unitd control socket: $SOCK_FILE"
+	        		ls -l $SOCK_FILE
+	        		exit 2
+	        	fi
+                fi
+        #fi ## end of IS_REMOTE check
+#### This is where we pass in ip and port
 	else
-		CURL_ADDR="http://$CTRL_ADDR"
+	     	#CURL_ADDR="http://$CTRL_ADDR"
+                CURL_ADDR="http://${REMOTE_IP}:${REMOTE_PORT}"
 	fi
 
 	# Get error log filename
